DROP TABLE IF EXISTS UserResource;
DROP TABLE IF EXISTS PostCommunity;
DROP TABLE IF EXISTS PostCategory;
DROP TABLE IF EXISTS UserSkill;
DROP TABLE IF EXISTS Message;

DROP TABLE IF EXISTS CustomMessage;
DROP TABLE IF EXISTS Membership;
DROP TABLE IF EXISTS Resource;
DROP TABLE IF EXISTS Review;
DROP TABLE IF EXISTS Skill;
DROP TABLE IF EXISTS Report;
DROP TABLE IF EXISTS Community;
DROP TABLE IF EXISTS Conversation;
DROP TABLE IF EXISTS Feedback;
DROP TABLE IF EXISTS CanceledPost;
DROP TABLE IF EXISTS Post;
DROP TABLE IF EXISTS Category;

DROP TABLE IF EXISTS User;












